# Generated by Django 5.0.2 on 2024-02-20 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('Company', models.CharField(max_length=255)),
                ('phone_number', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ship',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('ship_name', models.CharField(max_length=255)),
                ('ship_type', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='warehouse',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('warehouse_name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('amount_in_crores', models.IntegerField()),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
        ),
        migrations.CreateModel(
            name='route',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('duration', models.CharField(max_length=255)),
                ('distance', models.CharField(max_length=20)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_routes', to='main.location')),
                ('startlocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_routes', to='main.location')),
            ],
        ),
        migrations.CreateModel(
            name='shipment',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
                ('routes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.route')),
                ('ships', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ship')),
            ],
        ),
        migrations.CreateModel(
            name='package',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('contents', models.CharField(max_length=255)),
                ('shipments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shipment')),
                ('sup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.supplier')),
                ('ware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.warehouse')),
            ],
        ),
    ]
