# Generated by Django 5.0.2 on 2024-02-21 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Company',
            new_name='company',
        ),
    ]
