# Generated by Django 5.0.2 on 2024-02-26 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
