# Generated by Django 5.0.2 on 2024-03-01 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='cust',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='c',
        ),
        migrations.RemoveField(
            model_name='route',
            name='startlocation',
        ),
        migrations.RemoveField(
            model_name='route',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='package',
            name='shipments',
        ),
        migrations.RemoveField(
            model_name='package',
            name='sup',
        ),
        migrations.RemoveField(
            model_name='package',
            name='ware',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='routes',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='ships',
        ),
        migrations.DeleteModel(
            name='customer',
        ),
        migrations.DeleteModel(
            name='payment',
        ),
        migrations.DeleteModel(
            name='location',
        ),
        migrations.DeleteModel(
            name='supplier',
        ),
        migrations.DeleteModel(
            name='package',
        ),
        migrations.DeleteModel(
            name='warehouse',
        ),
        migrations.DeleteModel(
            name='route',
        ),
        migrations.DeleteModel(
            name='ship',
        ),
        migrations.DeleteModel(
            name='shipment',
        ),
    ]
