# Generated by Django 5.0.2 on 2024-03-01 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0005_remove_shipment_cust_remove_payment_c_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, unique=True)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_name', models.CharField(max_length=255, unique=True)),
                ('ship_type', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('phone', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.CharField(max_length=255, unique=True)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_in_crores', models.IntegerField()),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer', to_field='company')),
            ],
        ),
        migrations.CreateModel(
            name='route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('duration', models.CharField(max_length=255)),
                ('distance', models.CharField(max_length=20)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_routes', to='main.location', to_field='city')),
                ('startlocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_routes', to='main.location', to_field='city')),
            ],
        ),
        migrations.CreateModel(
            name='shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer', to_field='company')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.package', to_field='contents')),
                ('routes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.route', to_field='name')),
                ('ships', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ship', to_field='ship_name')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='sup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.supplier', to_field='name'),
        ),
        migrations.AddField(
            model_name='package',
            name='ware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.warehouse', to_field='warehouse_name'),
        ),
    ]
